<?php

namespace Tests\Feature\Billing;

use App\Models\BillingRevision;
use App\Models\PaymentReceipt;
use App\Models\User;
use App\Service\PaymentReceiptService;
use App\Service\StatementRevisionService;
use Illuminate\Foundation\Testing\LazilyRefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Tests\Concerns\BuildsBillingFixtures;
use Tests\TestCase;

/**
 * Billing documents carry the issuing centre's own logo, never a shared mark.
 *
 * A Statement of Account and a receipt are headed by the centre that issued
 * them: its logo, frozen at issue so a reprint matches the copy handed over,
 * or its initials when it has none. RedAgos is named only in the footer.
 */
class BillingDocumentBrandingTest extends TestCase
{
    use BuildsBillingFixtures, LazilyRefreshDatabase;

    private User $centreSupervisor;

    protected function setUp(): void
    {
        parent::setUp();

        Storage::fake('local');

        $this->setUpBillingFixtures();
        $this->priceComponent(500);
        $this->centreSupervisor = User::factory()->bloodCenterSupervisor($this->centre)->create();
    }

    public function test_a_statement_is_headed_by_the_issuing_centres_own_logo(): void
    {
        $this->uploadLogo(UploadedFile::fake()->image('logo.png', 40, 40));
        $request = $this->allocatedRequest(1);

        $revision = $this->issue($request)
            ->assertCreated()
            ->assertJsonPath('revision.issuer.name', $this->centre->name)
            ->json('revision');

        $this->assertStringContainsString('signature=', (string) $revision['issuer']['logo_url']);

        $html = $this->statementHtml(BillingRevision::query()->findOrFail($revision['id']));

        $this->assertStringContainsString('class="issuer-logo" src="data:image/png;base64,', $html);
        $this->assertStringContainsString(e($this->centre->name).' &middot; Statement of Account', $html);
        $this->assertStringContainsString('Generated by RedAgos', $html);
        $this->assertStringNotContainsString('Blood Bank Management', $html);
        $this->assertStringNotContainsString('class="mark"', $html);
    }

    public function test_a_centre_without_a_logo_is_headed_by_its_own_initials(): void
    {
        $this->centre->forceFill(['name' => 'Davao Regional Blood Center'])->save();
        $request = $this->allocatedRequest(1);

        $revision = $this->issue($request)
            ->assertCreated()
            ->assertJsonPath('revision.issuer.logo_url', null)
            ->json('revision');

        $html = $this->statementHtml(BillingRevision::query()->findOrFail($revision['id']));

        $this->assertStringContainsString('<div class="monogram">DR</div>', $html);
        $this->assertStringNotContainsString('class="issuer-logo"', $html);
    }

    public function test_a_statement_reprints_with_the_logo_it_was_issued_with(): void
    {
        $this->uploadLogo(UploadedFile::fake()->image('first.png', 40, 40));
        $first = $this->centre->fresh()->logo_path;

        $revisionId = $this->issue($this->allocatedRequest(1))->assertCreated()->json('revision.id');

        $this->uploadLogo(UploadedFile::fake()->image('second.png', 80, 20));

        // The issued statement still prints the first file, so it is kept.
        Storage::disk('local')->assertExists($first);
        $this->assertNotSame($first, $this->centre->fresh()->logo_path);

        $data = app(StatementRevisionService::class)->viewData(BillingRevision::query()->findOrFail($revisionId));

        $this->assertSame(
            'data:image/png;base64,'.base64_encode((string) Storage::disk('local')->get($first)),
            $data['logo']
        );
    }

    public function test_an_unprinted_logo_is_still_deleted_when_replaced(): void
    {
        $this->uploadLogo(UploadedFile::fake()->image('first.png', 40, 40));
        $first = $this->centre->fresh()->logo_path;

        $this->uploadLogo(UploadedFile::fake()->image('second.png', 40, 40));

        Storage::disk('local')->assertMissing($first);
    }

    public function test_a_documents_logo_link_serves_exactly_its_file_and_cannot_be_redirected(): void
    {
        $this->uploadLogo(UploadedFile::fake()->image('first.png', 40, 40));
        $url = (string) $this->issue($this->allocatedRequest(1))->assertCreated()->json('revision.issuer.logo_url');

        $this->assertStringContainsString('path=', $url);
        $this->get($url)->assertOk();

        $this->get(str_replace('path=facility-logos', 'path=other', $url))->assertForbidden();
    }

    public function test_a_receipt_is_headed_by_the_centres_logo_without_exposing_its_path(): void
    {
        $this->uploadLogo(UploadedFile::fake()->image('logo.png', 40, 40));
        $request = $this->allocatedRequest(1);

        $receipt = $this->payCash($request, 500)
            ->assertCreated()
            ->assertJsonPath('receipt.issuing_facility.name', $this->centre->name)
            ->json('receipt');

        $this->assertStringContainsString('signature=', (string) $receipt['issuing_facility']['logo_url']);
        $this->assertArrayNotHasKey('logo_path', $receipt['issuing_facility']);

        $service = app(PaymentReceiptService::class);
        $html = view('pdf.payment-receipt', $service->viewData(PaymentReceipt::query()->findOrFail($receipt['id'])))->render();

        $this->assertStringContainsString('class="issuer-logo" src="data:image/png;base64,', $html);
        $this->assertStringContainsString('Generated by RedAgos', $html);
        $this->assertStringNotContainsString('Blood Bank Management', $html);
    }

    private function uploadLogo(UploadedFile $file): void
    {
        $this->actingAs($this->centreSupervisor)
            ->post('/api/blood-center/facility/logo', ['logo' => $file], ['Accept' => 'application/json'])
            ->assertOk();
    }

    private function issue($request)
    {
        return $this->actingAs($this->billingClerk)
            ->postJson("/api/blood-center/billings/{$request->id}/statements");
    }

    private function statementHtml(BillingRevision $revision): string
    {
        return view('pdf.billing-statement', app(StatementRevisionService::class)->viewData($revision))->render();
    }
}
